package:
    name: odl
    version: "0.8.1"

source:
    git_url: https://github.com/odlgroup/odl
    git_rev: master  # development
    # git_rev: v0.7.0  # release
    # git_rev: a542c12d23da7fa5b92b360a51ea14e4804c58f6  # intermediate bugfix revision
    # path: ..  # for builds from local source (no download)

build:
    noarch: python
    number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=65.6

  run:
    - python >=3.7
    - setuptools <76.0
    - future >=0.16
    - numpy >=1.19, <1.27
    - scipy >=1.1
    - packaging >=17.0
    - matplotlib-base >=3.4

test:
  requires:
    - pytest >=5.4
  imports:
    - odl
  commands:
    - python -c "import odl; odl.test()"

about:
    home: https://github.com/odlgroup/odl
    license: MPL-2.0
    license_file: LICENSE
    summary: "Operator Discretization Library - a versatile Python framework for rapid prototyping in Inverse Problems and related fields"

extra:
    maintainers:
        - Ozan Öktem (@ozanoktem)
        - Justus Sagemüller (@leftaroundabout)
        - Emilien Valat (@Emvlt)
        # - Jonas Adler (@adler-j)
        # - Holger Kohr (@kohr-h)
